# Generated by Django 4.1.2 on 2022-10-09 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=256)),
                ("hometown", models.CharField(max_length=256)),
                ("clubhouse_location", models.CharField(max_length=256)),
                (
                    "established",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("achievement", models.TextField()),
            ],
        ),
    ]
