# Generated by Django 4.1.2 on 2022-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammodel",
            name="upated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="teammodel",
            name="established",
            field=models.DateField(default="1969, 7, 20"),
        ),
    ]
