# Generated by Django 4.1.2 on 2022-10-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footballapp", "0004_teammodel_description_teammodel_featured_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammodel", old_name="upated_date", new_name="updated_date",
        ),
    ]
