# Generated by Django 4.1.2 on 2022-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballapp", "0005_rename_upated_date_teammodel_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammodel",
            name="headcoach",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="headcoach_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="headline",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="logo",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammodel",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
