# Generated by Django 4.1.2 on 2022-10-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "footballapp",
            "0006_teammodel_headcoach_teammodel_headcoach_message_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=256)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("FW", "FW"),
                            ("MF", "MF"),
                            ("DF", "DF"),
                            ("GK", "GK"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "foot",
                    models.CharField(
                        choices=[("Right", "Right"), ("Left", "Left")], max_length=256
                    ),
                ),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("voice", models.TextField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Players",
                        to="footballapp.teammodel",
                    ),
                ),
            ],
        ),
    ]
