# Generated by Django 4.1.2 on 2022-10-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballapp", "0007_playermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermodel",
            name="number",
            field=models.IntegerField(default=1),
        ),
    ]
